### PR TITLE
don't change colours on blank lines

### LINKED ISSUE #24: empty/blank lines result in "missing" colors
Current situation & proposed fix:

Screenshot from 2020-06-19 15-16-31 cleaned

### PR DESCRIPTION
**Pull request by landfillbaby**
builds on @obfusk's changes. fixes #24

### CODE REVIEW

**Comment by obfusk** [comment]
The variable names are a bit inconsistent now: `g_blankLine` vs `g_changeEmpty`.
I originally only skipped "empty" lines. But now the code also handles "blank" (i.e. empty or only whitespace) lines.
I suggest renaming variables and command line options to use "blank".

**Comment by landfillbaby** [comment]
how's this?

**Comment by obfusk** [comment]
LGTM. I think it would be better to switch `Author`/`Co-authored-by` though.

You could maybe add `\f` and `\v` as blank characters.
Full-width spaces (`　`) might be a bit difficult to detect with the current code.
Not sure if there are other blank characters...

(`<shameless plug>`my [python version](https://github.com/obfusk/proudcat) skips all of these :sweat_smile:`</shameless plug>`)

**Comment by landfillbaby** [comment]
done

**Comment by obfusk** [comment]
Should

```c++
		if (c == '\n' || c == '\f' || c == '\v') {
[...]
		(c != ' ' && c != '\t' && c != '\r'))) {
```

not be

```c++
		if (c == '\n') {
[...]
		(c != ' ' && c != '\t' && c != '\r' && c != '\f' && c != '\v'))) {
```

instead?

**Comment by obfusk** [comment]
How about this?

```c++
#include <cctype>
[...]
else if (g_blankLine && (g_changeBlank || !isspace(c))) {
```

**Comment by landfillbaby** [comment]
i was thinking that since \f and \v both do effectively cause a new line, (at least they do on Android Termux, my PC is out of commission,) they should be treated as such, but if you think they should be ignored like the horizontal whitespace we can change it
and yes maybe isspace would be good to use

**Comment by obfusk** [comment]
I think `\f` and `\v` should normally not be found in the input anyway (I don't recall ever using them), and -- since different terminals don't always handle them identically -- only treating `\n` as newline is best. And `isspace` also makes the code a bit cleaner :) But I think there is probably no "correct answer" for all situations.

**Comment by obfusk** [comment]
Throw in some `\b`s and all bets are off :)

**Comment by landfillbaby** [comment]
ok yes. `\n` only, and `!isspace(c)` done

**Comment by landfillbaby** [comment]
closing in favour of #33

**Pull request closed without merging**
