### PR TITLE
improve truecolor terminal detection

### PR DESCRIPTION
**Pull request by obfusk**
(see https://gist.github.com/XVilka/8346728)

### CODE REVIEW

**Comment by lunasorcery** [comment]
I'm not sure about `-n` for the flag, maybe `-T` as a more logical counter to `-t`?

Otherwise this looks like a good change! ✨

**Comment by obfusk** [comment]
I wasn't sure about `-n` either; changed to `-T`.

**Comment by lunasorcery** [comment]
Great! If you can just add it to the README as well then I'll happily get this merged :)

**Comment by obfusk** [comment]
Forgot about the README :sweat_smile:, done.

**Pull request merged**
