### PR TITLE
don't change color on empty lines

### LINKED ISSUE #24: empty/blank lines result in "missing" colors
Current situation & proposed fix:

Screenshot from 2020-06-19 15-16-31 cleaned

### PR DESCRIPTION
**Pull request by obfusk**
fixes #24

### CODE REVIEW

**Comment by obfusk** [comment]
Screenshot from 2020-06-19 15-16-31 cleaned

**Comment by landfillbaby** [comment]
this doesn't fix in the case of a line containing only spaces or tabs

**Comment by obfusk** [comment]
> this doesn't fix in the case of a line containing only spaces or tabs

Fixed.

**Comment by obfusk** [comment]
Closing b/c @landfillbaby has a better version.

**Comment by landfillbaby** [comment]
oh ok i'll make a pr for mine then :)

**Comment by obfusk** [comment]
@landfillbaby You can use `Co-authored-by` to share the credit if you want :)

**Comment by landfillbaby** [comment]
i think that's just for single commits, unless we squash them i think having your name on your commits is ok? i was originally planning on having you merge my changes into your branch and then that being merged into the original

**Comment by obfusk** [comment]
@landfillbaby I assumed squashing the commits for a new PR would be cleaner. Either way is fine with me.

**Pull request closed without merging**
